apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatk8s
  labels:
    app: eatk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eatk8s
  template:
    metadata:
      labels:
        app: eatk8s
    spec:
      containers:
          - name: eatk8s
            image: mreider/eatk8s:1.0
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            env:                     # Environment variables passed to the container
              - name: REDIS_HOST
                value: redis-master
              - name: REDIS_PORT
                value: "6379"
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: eatk8s-service     # Unique name of the resource
spec:
  type: NodePort                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 4567
    targetPort: 4567
  selector:
    app: eatk8s         